backend:
  name: github
  repo: kre1z0/kre1z0.github.io
  branch: ES-128

media_folder: static/img
public_folder: /img

collections:
  - name: "about"
    label: "Сми о нас"
    widget: "string"
    folder: "src/data/about"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
      - {label: "Заголовок", name: "title", widget: "string"}
      - {label: "Дата публикации", name: "date", widget: "datetime"}
      - {label: "Краткое описание", name: "description", widget: "text"}
      - {label: "Ссылка", name: "link", widget: "string"}
      - {label: "Логотип", name: "logo", widget: image}
      - {label: "Отображать на главной", name: "isVisible", widget: "boolean", default: false}
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/data/pages/about.md"
        label: "Сми о нас"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about"}
          - {label: "Title", name: "Имя блока", widget: "string"}
